### PR TITLE
Better error messages for autograder settings

### LINKED ISSUE #2141: AutogradersController methods should use @autograders.errors in flash
When `@autograders.save` fails, the controller methods should use the `@autograders.errors` in the flash error messages, like assessment settings do.

### PR DESCRIPTION
**Pull request by damianhxy**
## Description

- Change bounds of autograder timeout to be inclusive (10 to 900 seconds)
- Remove unnecessary javascript code from form (handled by Materialize)
- Change to new style path helpers
- Better frontend validation of `autograde_image` (present and length <= 64) and `autograde_timeout` (numeric field + bounds), show bounds in help text
- Remove unmaintained/deprecated `dynamic_form` gem + all occurrences of `error_messages`
- Make edit assessment update failure message consistent
- Use `notice` instead of `error` for warn messages so that it doesn't overwrite update failure messages

## Motivation and Context

Removes all `f.error_messages` occurrences + removes the `dynamic_form` gem as the gem has not really been maintained since Rails 3 (https://rubygems.org/gems/dynamic_form/versions/1.1.4?locale=en)

Besides, it isn't particularly necessary.

Closes #2141

## How Has This Been Tested?

- Autograde timeout can now be set to 10s / 900s inclusive
- Observe helptext explaining that timeout "Must be between 10s and 900s, inclusive."
- When choosing a Autograder Makefile or Autograder Tar, the file name still updates correctly
- Make frontend validation better reflect backend validation
  - `autograde_image` can't be empty
  - `autograde_image` can't be longer than 64 chars
  - `autograde_timeout` must be numeric, and between 10 and 900 inclusive
- If backend validation fails (you have to disable the frontend validation first), helpful error message displayed
Screenshot 2024-04-06 at 12 22 22

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run rubocop and erblint for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://docs.autolabproject.com/)
- [ ] I have updated the documentation accordingly, included in this PR

## Summary by CodeRabbit

- **New Features**
	- Added more structured and informative feedback for late submissions and assessment configuration errors.
	- Enhanced validation for autograder timeout settings, ensuring values are between 10 and 900 seconds.
- **Bug Fixes**
	- Updated flash messages across various actions for clearer communication.
	- Improved form validation and error messaging, particularly for autograder configurations.
- **Refactor**
	- Removed outdated `dynamic_form` gem and associated error message calls in forms, streamlining error handling.
- **Style**
	- Updated form fields for autograder configurations, including changing input types and adding constraints.

### CODE REVIEW

File: app/controllers/assessments_controller.rb [hunk 1]
```diff
@@ -839,7 +839,9 @@ def edit
                           without grace days are not penalized"
       end
       unless warn_messages.empty?
-        flash.now[:error] = "Late submissions are allowed, but<br>#{warn_messages.join('<br>')}"
+        flash.now[:notice] = "Late submissions are allowed, but<br>"
```
Comment (jlge) [inline app/controllers/assessments_controller.rb:842]: side note this was such a good idea wow I never knew this was a thing

**Review by jlge — APPROVED** [review]
LGTM 👏
