### PR TITLE
Sort scoreboard beyond third column, improve CUD validations

### LINKED ISSUE #970: Scoreboard Column Specification does not work if asc/desc is defined beyond third column
A colleague is currently implementing a scoreboard with six columns and ran into trouble when he added "asc": 1 to the json-definition of certain columns. Some experimenting suggests that this happens only for beyond column 3. This means the following json works fine:
```
{"scoreboard":[{"hdr":"1", "asc":1},{"hdr":"2", "asc":1},{"hdr":"3", "asc": 1},{"hdr":"4"},{"hdr":"5"},{"hdr":"6"}]}
```
while the following is ignored:
```
{"scoreboard":[{"hdr":"1", "asc":1},{"hdr":"2", "asc":1},{"hdr":"3", "asc": 1},{"hdr":"4", "asc" : 1},{"hdr":"5"},{"hdr":"6"}]}
```
The reason for this seems to be the condition that a 'asc' or 'desc' key is only accepted in columns with index smaller than three in `/app/controllers/scoreboards_controller.rb`, for reasons that were unclear to me:
https://github.com/autolab/Autolab/blob/d914dc8f1e8110e887657b5eb51169f8adc153b3/app/controllers/scoreboards_controller.rb#L198

The main issue seems to be that sorting is done in the `scoreboardOrderSubmissions` method in the same file does a hard-coded sorting for three elements. Maybe it would be an idea to use a generale comparison, or add a warning to the colspec-page.

### PR DESCRIPTION
**Pull request by damianhxy**
### Summary generated by Reviewpad on 21 Jun 23 18:44 UTC
This pull request includes changes to several files. The file 'scoreboards.md' has a minor change, sorting all columns in descending order and tie-breaking by submission time. The view file 'app/views/course_user_data/new.html.erb' has several updates, including adding a javascript_include_tag and modifying the onclick function of the submit button. The Scoreboard view has also been updated in the 'scoreboard.rb' file in the 'app/models' directory, including a validation check for the column specification and refactored code to handle all scoreboard columns. Changes have been made to the `CourseUserDataController` in the Rails application, including modifying error messages and allowing for HTML in the flash[:error] message. The form validation function and nickname validation method have also been updated.

## Description

- Refresh scoreboard#show page
- Scoreboard now sorts all columns, not just up to the third column
- Update docs to reflect change
- Fix CUD form validation
- Remove unnecessary error display code: they basically don't work because errors (during create / update) are cleared during redirects, so this PR uses flashes instead. A user would not be able to load the scoreboard if they had errors in their CUD because they would have been redirected to the edit page.

## Motivation and Context

Currently, only the first three columns of any scoreboard is sorted (when using a custom column specification). This PR remedies that so all columns are now sorted.

Note: I don't expect this to break any scoreboard code, since scoreboards generally consist of numeric data. Even if they contain string data, `to_f` casts non-numeric strings to `0.0`, which is as good as not sorting.

Closes #970

Furthermore, the custom form validation for the nickname fields is currently broken and does not work. Validation errors are also not shown since a redirect takes place.

This PR fixes the validation code, shows errors in flashes instead, and adds more visual cues (e.g. set `maxlength` = 32, indicate in help text)

## How Has This Been Tested?

Install the following assessment (after unzipping): 
[randomlab_20230616.tar.zip](https://github.com/autolab/Autolab/files/11767997/randomlab_20230616.tar.zip)

Submit any file using three different student accounts. View scoreboard.

### Before
Specification: `{"scoreboard": [ {"hdr":"Problem 1"}, {"hdr":"Problem 2"}, {"hdr":"Problem 3"}, {"hdr":"Problem 4"}, {"hdr":"Problem 5"}, {"hdr":"Problem 6"} ] }`
Observe: `PROBLEM 6` (no `asc` or `desc`)
Screenshot 2023-06-16 at 15 16 20

Observe: last column not sorted (tiebreak by time)
Screenshot 2023-06-16 at 15 16 28

### After (Descending)
Specification: `{"scoreboard": [ {"hdr":"Problem 1"}, {"hdr":"Problem 2"}, {"hdr":"Problem 3"}, {"hdr":"Problem 4"}, {"hdr":"Problem 5"}, {"hdr":"Problem 6"} ] }`
Observe: `PROBLEM 6 [desc]`
Screenshot 2023-06-16 at 15 14 11

Observe: last column sorted in descending order
Screenshot 2023-06-16 at 16 27 52

### After (Ascending)
Specification:  `{"scoreboard": [ {"hdr":"Problem 1"}, {"hdr":"Problem 2"}, {"hdr":"Problem 3"}, {"hdr":"Problem 4"}, {"hdr":"Problem 5"}, {"hdr":"Problem 6", "asc": 1} ] }`
Observe: `PROBLEM 6 [asc]`
Screenshot 2023-06-16 at 15 14 43

Observe: last column sorted in ascending order
Screenshot 2023-06-16 at 16 28 11

### Others
- Check documentation

Column specification
- Try saving a specification of `true` -> get error `Colspec must be a hash object`
- Try saving a specification which is missing quotes around one of the strings -> get error (similar to) `Colspec 451: unexpected token at '{hdr:"Problem 6"} ] }'`

Form validation
- Test form validation on scoreboard page, edit CUD, new CUD pages: attempt to save nickname with non-ascii characters (e.g. 你好) -> observe alert, and highlighting + focusing of nickname field
Screenshot 2023-06-16 at 16 24 11
Screenshot 2023-06-16 at 16 24 14

- Observe helptext additionally states "(maxlength: 32)"
Screenshot 2023-06-16 at 16 28 35

Screenshot 2023-06-16 at 16 28 49

- You can also disable frontend validation and try saving a nickname of length > 32 and with non-ascii characters (e.g. `12345678123456781234567812345678你好`)

**Updating via Scoreboard or Edit page**

Screenshot 2023-06-16 at 16 35 07

**Creation**

Screenshot 2023-06-22 at 02 43 08

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [x] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [x] I have updated the documentation accordingly, included in this PR

### CODE REVIEW

File: app/models/scoreboard.rb [hunk 1]
```diff
@@ -24,14 +24,17 @@ def colspec_is_well_formed
 
     # The parse will throw an exception if the string has a JSON syntax error
     begin
-      # Quote JSON keys and values if they are not already quoted
-      quoted = colspec.gsub(/([a-zA-Z0-9]+):/, '"\1":').gsub(/:([a-zA-Z0-9]+)/, ':"\1"')
```
Comment (damianhxy) [inline app/models/scoreboard.rb:28]: I remove the quoting here because otherwise unquoted colspecs will pass validations. This causes problems in `show` and `scoreboardOrderSubmissions` which do not perform quoting. Rather than quote at all three places, it makes more sense to enforce good syntax from the user.

File: app/views/scoreboards/show.html.erb [hunk 2]
```diff
@@ -73,19 +75,14 @@
 <% end %>
 
 
-<%= form_for @cud, url: course_course_user_datum_path(@course, @cud) do |f| %>
-<% if @cud.errors.any? %>
```
Comment (damianhxy) [inline app/views/scoreboards/show.html.erb:77]: Unnecessary since a user shouldn't be able to view the scoreboard if they have errors. `authorize_user_for_course` would have redirected users to the edit info page.

**Comment by damianhxy** [comment]
Note to self: add a way to skip sorting a column

File: app/views/course_user_data/_fields.html.erb [hunk 3]
```diff
@@ -7,7 +7,7 @@
 
   <% end %>
 
-  <%= f.text_field :nickname, help_text: "Anonymous nickname to display on the public scoreboards", placeholder: "droh" %>
+  <%= f.text_field :nickname, help_text: "Anonymous nickname to display on the public scoreboards (maxlength: 32)", placeholder: "droh", maxlength: 32 %>
```
Comment (najclark) [inline app/views/course_user_data/_fields.html.erb:10]: nit: add space in maxlength

**Review by najclark — APPROVED** [review]
lgtm, testing behavior looks correct

File: app/views/course_user_data/_fields.html.erb (hunk 3 above)
Comment (damianhxy) [reply app/views/course_user_data/_fields.html.erb]: Fixed (PR description not updated)

Also made a small modification to the creation error message to make it consistent with the update error message.
