### PR TITLE
Hide unreleased attachments

### LINKED ISSUE #1375: Unreleased handout shown to students
**Your environment**
Ubuntu 18.04, Autolab master branch.

**Steps To Reproduce**
1. Add an attachment to a homework, leaving "Released" unchecked.
2. View the homework as a student. Scroll down to the "Handouts" section.
3. Click on the handout we just created.

**Current behavior**
The unreleased handout is listed under "Handouts", and is accessible after clicking on it.

**Expected behavior**
In my understanding, the unreleased handout should not be listed or accessible.

**Screenshots**
An unreleased handout

This handout has the "Released" box unchecked.

The unreleased handout is listed on homework page

But it shows up when a student visits the homework (`/courses/AutoPopulated/assessments/homework3`). If I click on the "Unreleased handout" link, the PDF content is returned.

The unreleased handout is hidden on course page

However, it is correctly hidden on the course home page (`/courses/AutoPopulated/assessments`).

### PR DESCRIPTION
**Pull request by damianhxy**
## Description
- Hides unreleased attachments from view when viewing an assessment.
- Prevents users from directly accessing an unreleased attachment (via id manipulation).
- Standardizes attachment display style of course vs assessment

## Motivation and Context
Currently, unreleased attachments are not being correctly hidden when we view an assessment.

Besides, there is no verification before allowing a user to download an attachment. So currently an unreleased attachment can be viewed by modifying the id in the url (which is really bad).

Fixes #1375

## How Has This Been Tested?
- Add released and unreleased attachments to course
- Add released and unreleased attachments to an assessment
- When viewing course or viewing assessment, only released attachments should be viewable
- Downloading released attachments works as usual
- Attempting to directly access an unreleased assessment attachment results in an error, and redirects user to the assessment page
- Attempting to directly access an unreleased course attachment results in an error, and redirects user to the course page

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run rubocop for style check. If you haven't, run `overcommit --install && overcommit --sign` to use pre-commit hook for linting
- [ ] My change requires a change to the documentation, which is located at [Autolab Docs](https://github.com/autolab/docs)
- [ ] I have updated the documentation accordingly, included in this PR

## Other issues / help required
Unsure if the `conditionals` and/or `redirect_to` follows best practices

### CODE REVIEW

File: app/controllers/assessments_controller.rb [hunk 1]
```diff
@@ -450,6 +450,11 @@ def show
                     else
                       @cud
                     end
+    @attachments = if @cud.instructor?
+                     @course.attachments
```
Comment (michellexliu) [inline app/controllers/assessments_controller.rb:454]: I think this should be `@assessment.attachments`, rather than `@course` so that the handouts shown are specific to the assessment page currently shown, rather than whole course

**Review by michellexliu — CHANGES_REQUESTED** [review]

**Review by michellexliu — APPROVED** [review]
lgtm!
