### PR TITLE
Fixed Grader Info in Submission Popover

### LINKED ISSUE #201: Grade Submissions page: Adding feedback to a score sometime fails
When trying to add feedback to a score, the feedback box pops up and then DKs inside the box the first time, and thereafter, clicking the score doesn't pop up any feedback box. This doesn't occur for every course or assessment. To consistently reproduce this, visit 18447-s15, lab1,a*****r@andrew, and try to add feedback to his score (see screenshot below).

The problem only shows up for certain assessments, even in the same course. For example, 15122-s15,Written 1 is fine for all students and all problems. However, for 15122-s15,Quiz 0, it fails for all students. 

5640038c-a63e-11e4-905a-a355aa6152c2

### PR DESCRIPTION
**Pull request by dlbucci**
Fixes #201 and #202.

### CODE REVIEW

File: app/controllers/assessment/grading.rb [hunk 1]
```diff
@@ -286,8 +286,9 @@ def submission_popover
   end
 
   def score_grader_info
-    grader = Score.find(params[:id]).grader
-    if grader
```
Comment (icanberk) [inline app/controllers/assessment/grading.rb]: who wrote this? how did this ever work without `then`?

Comment (ymzong) [inline app/controllers/assessment/grading.rb]: @icanberk Apparently the new Rails overrode `params[:id]` with the id of the controller, i.e. assessment.

Comment (dlbucci) [inline app/controllers/assessment/grading.rb]: @icanberk ruby if statements don't need to have a then unless the block is on the same line (if true then blah end), but I think it's good practice to have then's at the end of if statements.
